version: "3.7"

networks:
  dockered:

services:

  php:
    image: dumptec/php-fpm:dev-8.2-latest
    hostname: php
    user: "dump"
    working_dir: /app
    dns: 1.1.1.1
    depends_on:
      - docker-api
    links:
      - docker-api
    networks:
      - dockered
    volumes:
      - ./:/app

  docker-api:
    hostname: docker-api
    image: docker:dind
    dns: 1.1.1.1
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
      DOCKER_HOST: tcp://0.0.0.0:2375
    networks:
      - dockered